name: Yuzu Audio
exclude: ["README.md", "Gemfile", "Gemfile.lock", "CNAME"]
timezone: Europe/London
url: http://www.yuzuaudio.com

gems:
  - jekyll-sitemap

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "drafts"
    values:
      layout: "post"
