name: Yuzu Audio
exclude: ["README.md", "Gemfile", "Gemfile.lock", "CNAME"]
timezone: Europe/London
url: https://www.yuzuaudio.com

plugins:
  - jekyll-sitemap

collections:
  kits:
    output: true
    permalink: /:collection/:name/
  manufacturers:
    output: true
    permalink: /:collection/:name/
  parts:
  specs:
  boms:

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "drafts"
    values:
      layout: "post"
